name = "PowerParser"
uuid = "14903efe-9500-4d7f-a589-7ab7e15da6de"
authors = ["Archim Jhunjhunwala <archimj@mit.edu>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PGLib = "07a8691f-3d11-4330-951b-3c50f98338be"

[compat]
JLD2 = "~0.5"
PGLib = "0.2.1"
PowerModels = "~0.21"
Test = "~1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PowerModels"]
benchmark = ["PowerModels", "BenchmarkTools"]
